[package]
name = "cli-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
prettytable-rs = "0.10.0"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
